# Dockerfile.dev
FROM node:18-alpine AS dev

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy full app for development
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]