version: "3.8"
services:
    frontend-dev:
        build:
            context: ./frontend
            target: dev
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        # depends_on:
        #   - backend
        environment:
            NEXT_PUBLIC_API_URL: http://backend:8000

    frontend-prod:
        build:
            context: ./frontend
            target: prod
        ports:
            - "3000:3000"
        # depends_on:
        #   - backend
        environment:
            NEXT_PUBLIC_API_URL: http://backend:8000

    backend:
        build: ./backend
        ports:
            - "8000:8000"
        depends_on:
            - kafka
        environment:
            KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
            - "2181:2181"
